using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace quest4dealsweb.Server.models;
public class GamePriceHistory
{
    public int Id { get; set; } // Auto-generated by DB
    public int GameId { get; set; }
    public decimal Price { get; set; }
    public DateTime RecordedAt { get; set; }
    // Optional: public Game Game { get; set; } (navigation property, not in request)
}