name: Deploy ASP.NET Backend to Elastic Beanstalk

on:
  push:
    branches:
      - Develop
    paths:
      - 'quest4dealsweb.Server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Publish .NET Web API
      run: dotnet publish quest4dealsweb.Server/quest4dealsweb.Server.csproj -c Release -o publish

    - name: Zip publish folder
      run: zip -r deploy.zip publish

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.EB_APPLICATION_NAME }}
        environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
        version_label: backend-${{ github.run_number }}
        region: ${{ secrets.AWS_REGION }}
        deployment_package: deploy.zip
