name: CI Pipeline

on:
  push:
    branches:
      - Develop
  pull_request:
    branches:
      - Develop

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

  frontend:
    needs: backend  # Optional: runs after backend if required
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Frontend Dependencies
        run: |
          cd quest4dealsweb.client
          npm install react-chartjs-2 chart.js
          npm install

      - name: Build Frontend
        run: |
          cd quest4dealsweb.client
          npm run build
